name: Will Barrett
meta_description: "Will Barrett is a software developer."

aboutPage: true

markdown: redcarpet
highlighter: pygments

# paginate: 20
baseurl: /
domain_name: 'http://willbarrett.github.io'
google_analytics: 'UA-68358208-1'
disqus: false
disqus_shortname: 'tallgreentree'

# Details for the RSS feed generator
url:            'http://willbarrett.github.io'
author:         'Will Barrett'
authorTwitter:  'willbarrettdev'

permalink:       /:year/:title/
exclude: 
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
