name: Will Barrett
description: Valiantly struggling against the computing revolution
meta_description: "Will Barrett is a software developer."

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://willbarrett.github.io'
google_analytics: 'UA-XXXXXXXX-X'
disqus: true
disqus_shortname: 'tallgreentree'

# Details for the RSS feed generator
url:            'http://willbarrett.github.io'
author:         'William Barrett'
authorTwitter:  'willbarrettdev'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
